apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-k6
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
data:
  {{ range $path, $_ :=  .Files.Glob  "k6scripts/**.js" }}
  {{- $scriptName := regexReplaceAll "(^.*/)(.*)\\.js$" $path "${2}" }}
  {{ $scriptName }}.js: |
{{ $.Files.Get $path | indent 4 }}
  {{ end }}
