apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-grdata
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
{{- $files := .Files.Glob "*-datasource.yaml" }}
{{- if $files }}
{{- range $path, $fileContents := $files }}
  datasource.yaml: {{ $.Files.Get $path | quote }}
{{- end }}
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-grdash
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
{{- $files := .Files.Glob "*-dashboard.yaml" }}
{{- if $files }}
{{- range $path, $fileContents := $files }}
  dashboard.yaml: {{ $.Files.Get $path | quote }}
{{- end }}
{{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-gr
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
{{- $files := .Files.Glob "grafana/dashboards/*.json" }}
{{- if $files }}
{{- range $path, $fileContents := $files }}
{{- $dashboardName := regexReplaceAll "(^.*/)(.*)\\.json$" $path "${2}" }}
  {{ $dashboardName }}.json: {{ $.Files.Get $path | quote }}
{{- end }}
{{- end }}
