apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-db
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
{{- $files := .Files.Glob "*.json" }}
{{- if $files }}
{{- range $path, $fileContents := $files }}
{{- $dashboardName := regexReplaceAll "(^.*/)(.*)\\.json$" $path "${2}" }}
  {{ $dashboardName }}.json: {{ $.Files.Get $path | quote }}
{{- end }}
{{- end }}