apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loadtest-infra.fullname" . }}-grafana-depl
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-grafana-depl
    app.kubernetes.io/instance: {{ .Release.Name }}-grafana-depl
    {{- include "loadtest-infra.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.grafana.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-grafana
      app.kubernetes.io/instance: {{ .Release.Name }}-grafana
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-grafana
        app.kubernetes.io/instance: {{ .Release.Name }}-grafana
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "loadtest-infra.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-grafana
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.grafana.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          command: ["nslookup","19.1.10.1"]
          ports:
            - name: http
              containerPort: {{ .Values.grafana.port }}
              protocol: TCP
          env:
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: "Admin"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_SERVER_SERVE_FROM_SUB_PATH
            value: "true"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config-dashboards
            mountPath: /var/lib/grafana/dashboards
          - name: config-datasource
            mountPath: /etc/grafana/provisioning/datasources
          - name: config-dash
            mountPath: /etc/grafana/provisioning/dashboards
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config-dashboards
        configMap: 
          name: {{ .Release.Name }}-cm-gr
      - name: config-datasource
        configMap: 
          name: {{ .Release.Name }}-cm-grdata
      - name: config-dash
        configMap: 
          name: {{ .Release.Name }}-cm-grdash
