apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ uuidv4 | substr 0 5 }}-k6-job
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-k6
        app.kubernetes.io/instance: {{ .Release.Name }}-k6
    spec:
      restartPolicy: OnFailure
      containers:
     {{- range .Values.k6.scripts }}
      - name: k6-{{ . | lower }}
        image: "{{ $.Values.k6.image }}"
        args: ["run" ,"/scripts/{{ . }}.js"]
        env:
        - name: K6_OUT
          value: "influxdb=http://influxdb:31111/K6"
        volumeMounts:
        - name: {{ $.Release.Name }}-cm-k6-vol
          mountPath: /scripts
     {{- end }}

      volumes:
      - name: {{ .Release.Name }}-cm-k6-vol
        configMap: 
          name: {{ .Release.Name }}-cm-k6

