apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-infra.fullname" . }}-grafana-ext-svc
  labels:
    {{- include "loadtest-infra.labels" . | nindent 4 }}    
spec:
  type: LoadBalancer
  ports:
    - port: 3010
      targetPort: {{ .Values.grafana.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-grafana
    app.kubernetes.io/instance: {{ .Release.Name }}-grafana

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
#  name: {{ include "loadtest-infra.fullname" . }}-db-svc
  labels:
    {{- include "loadtest-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 31111
      targetPort: {{ .Values.db.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}-db

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-infra.fullname" . }}-grafana-svc
  labels:
    {{- include "loadtest-infra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 31112
      targetPort: {{ .Values.grafana.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-grafana
    app.kubernetes.io/instance: {{ .Release.Name }}-grafana
