apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadtest-infra.fullname" . }}
  labels:
    {{- include "loadtest-infra.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.grafana.port }}
      targetPort: {{ .Values.grafana.port }}
      nodePort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "loadtest-infra.name" . }}-grafana
    app.kubernetes.io/instance: {{ .Release.Name }}-grafana
